DROP TABLE MEMBER;

--이름 전화번호 주소 이메일
CREATE TABLE MEMBER(
	NAME VARCHAR2(20),
	PHONE VARCHAR2(20),
	ADDR VARCHAR2(100),
	EMAIL VARCHAR2(40)
);
INSERT INTO MEMBER VALUES('KIM','010-1234-5678','서울 어딘가','KIM@MAIL.COM');

SELECT NAME, PHONE, ADDR, EMAIL FROM MEMBER ORDER BY NAME;